name: Build and deploy Node.js app to Azure Web App - app-kenq-2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install, build, test
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_AZURE_API_URL: ${{ vars.NEXT_PUBLIC_AZURE_API_URL }}
        run: |
          npm ci --no-audit --no-fund
          npm run build --if-present
          npm run test --if-present

      # Next.js の standalone 出力を最小構成でまとめる
      - name: Prepare deploy bundle
        run: |
          rm -rf deploy
          mkdir -p deploy/.next/static
          cp -r ./.next/standalone/* ./deploy/
          cp -r ./public ./deploy/ || true
          cp -r ./.next/static/* ./deploy/.next/static/ || true

      - name: Zip for deployment (no artifacts)
        run: |
          cd deploy
          zip -r ../release.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-kenq-2'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_579972AA670F4E95B95B25614E397BD0 }}

