name: Build & Deploy Next.js (standalone) - app-kenq-2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install deps & build Next.js
        run: |
          npm ci
          # standalone 出力（Next 13+推奨）
          npm run build

      - name: Prepare deploy folder
        run: |
          mkdir -p deploy
          # Next.js standalone 方式の必須物をまとめる
          cp -r .next/standalone/* deploy/
          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/static
          [ -d public ] && cp -r public deploy/public || true
          # package.json, next.config.js 等が必要なら適宜コピー
          [ -f package.json ] && cp package.json deploy/ || true

      - name: Deploy to Azure Web App (no artifacts)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-kenq-2'
          slot-name: 'Production'
          package: ./deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CD12AE63977F4F9AA66289B6BC33CBE5 }}
